on: [workflow_call]

name: Install Treesitter

jobs:
  install-treesitter:
    name: Install Treesitter
    runs-on: ubuntu-latest
    steps:
      - run: env
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
      - uses: tree-sitter/setup-action@v2
        with:
          install-cli: true
  generate-grammar:
    name: Install Treesitter
    runs-on: ubuntu-latest
    needs: install-treesitter
    steps:
      - uses: actions/checkout@v2
      - run: /opt/hostedtoolcache/tree-sitter/cli/bin/tree-sitter generate
        working-directory: ./tree-sitter-p4

